### ISSUE TITLE
Extract ProjectCompiler members into separate class

### ISSUE THREAD

**Issue by bduisenov** [cacozzzz/mockifyHoster#1]
ProjectCompiler methods for loading and saving should be extracted into separate class, that will take care for file persistence.

This should be done in order to make operations related to file and use case logic itself loosely coupled. As a consequence, this will allow us to swap implementation, like changing to db persistence or what so ever in a future without a need to touch use case at all.

Through couple of iterations, we will come to a state of really loosely coupled components. As for now, we start with extraction.

**Comment by a-sergiyenko** [comment]
done
