### ISSUE TITLE
Refactor static ProjectCompiler

### ISSUE THREAD

**Issue by bduisenov** [cacozzzz/mockifyHoster#2]
You should tend to avoid using a `static` as much as you can. 

1. `static` members of a `class` are hard to test. 
I'll show this part when we will start using `mockito` and `junit` mocking.

2. imposible to override
If you have a class for example:
```
class A {
  static void doSomething() { ... }
}
```
you are not able to override the `#doSomething` method, because it belongs to `A.class` and not to an instance of a class. So 
```
class B extends A {
  @Override  
  static void doSomething() { ... }
}
```
will not work.

**Comment by a-sergiyenko** [comment]
done
