### ISSUE TITLE
Working with java.nio.file.Paths

### ISSUE THREAD

**Issue by bduisenov** [cacozzzz/mockifyHoster#7]
having this kind of statements is not a good practice, because it is `OS` dependent. For example, this would not work with `*nix`

```
   Path path = Paths.get(getTempDirectory()
                + "\\" + testProjectsDataFolder
                + "\\" + testProjectFolder
                + "\\" + testProjectFileName);
```
Instead, you should use a `varargs` arguments of `Paths#get`. It means that the code should look like `Paths.get(getTempDirectory(), testProjectsDataFolder, testProjectFolder, testProjectFileName);`

**Comment by a-sergiyenko** [comment]
Shame, shame, shame :-) Fixed
👍
